name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]  # or master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: (Optional) Start Server for test
      run: |
        echo "Start script exists: checking if server starts"
        npm start
